name: Deploy website
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Installing the dependencies
        run: npm ci

      - name: Linting the code
        run: npm run lint

      - name: Testing the code
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Installing the dependencies
        run: npm ci

      - name: Building website
        run: npm run build

      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

      - name: Generating job artifacts
        uses: actions/upload-artifact@v3
        with:
          name: My artifacts
          path: dist
          # path: |
          #   dist
          #   package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the generated build artifacts
        uses: actions/download-artifact@v3
        with:
          name: My artifacts

      - name: Output content
        run: ls

      - name: Outputting filename
        run: echo "${{ needs.build.outputs.script-file }}"

      - name: Deploy
        run: echo "Deploying..."
